In [3]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X=np.arange(9).reshape(3,3)
poly=PolynomialFeatures(degree=2)
print(X)
print(poly.fit_transform(X))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 1.  0.  1.  2.  0.  0.  0.  1.  2.  4.]
 [ 1.  3.  4.  5.  9. 12. 15. 16. 20. 25.]
 [ 1.  6.  7.  8. 36. 42. 48. 49. 56. 64.]]


In [4]:
from sklearn.decomposition import PCA
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca = PCA(n_components=1)
pca.fit(X)
print(pca.transform(X))

[[ 1.38340578]
 [ 2.22189802]
 [ 3.6053038 ]
 [-1.38340578]
 [-2.22189802]
 [-3.6053038 ]]


In [6]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
bcls=BaggingClassifier(DecisionTreeClassifier(),max_samples=0.5, max_features=0.5, n_estimators=50)
X,y=datasets.make_blobs(n_samples=8000,centers=2, random_state=0,
cluster_std=4)
bcls.fit(X,y)
print(bcls.score(X,y))

0.94925


In [11]:
from sklearn import model_selection
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier
from sklearn import datasets

In [13]:
def vclas(w1,w2,w3, w4):
    X , y = datasets.make_classification(n_features= 10, n_informative=4,
    n_samples=500, n_clusters_per_class=5)
    Xtrain,Xtest, ytrain,ytest= cross_validation.train_test_
    split(X,y,test_size=0.4)
    clf1 = LogisticRegression(random_state=123)
    clf2 = GaussianNB()
    clf3 = RandomForestClassifier(n_estimators=10,bootstrap=True, random_state=123)
    clf4= ExtraTreesClassifier(n_estimators=10, bootstrap=True,random_state=123)
    clfes=[clf1,clf2,clf3,clf4]
    eclf = VotingClassifier(estimators=[('lr', clf1), ('gnb', clf2),
    ('rf', clf3),('et',clf4)],voting='soft', weights=[w1, w2, w3,w4])
    [c.fit(Xtrain, ytrain) for c in (clf1, clf2, clf3,clf4, eclf)]
    N = 5
    ind = np.arange(N)
    width = 0.3
    fig, ax = plt.subplots()
    for i, clf in enumerate(clfes):
        print(clf,i)
        p1=ax.bar(i,clfes[i].score(Xtrain,ytrain,),
        width=width,color="black")
        p2=ax.bar(i+width,clfes[i].score(Xtest,ytest,),
        width=width,color="grey")
    ax.bar(len(clfes)+width,eclf.score(Xtrain,ytrain,),
    width=width,color="black")
    ax.bar(len(clfes)+width *2,eclf.score(Xtest,ytest,),
    width=width,color="grey")
    plt.axvline(3.8, color='k', linestyle='dashed')
    ax.set_xticks(ind + width)
    ax.set_xticklabels(['LogisticRegression',
    'GaussianNB', 'RandomForestClassifier',
    'ExtraTrees', 'VotingClassifier'], rotation=40,
    ha='right')
    plt.title('Training and test score for different classifiers')
    plt.legend([p1[0], p2[0]], ['training', 'test'], loc='lower left')
    plt.show()