In [1]:
import numpy as np
#creating arrays
a_list = [1,2,3]
an_array = np.array(a_list)
#Specify the datatype
an_array = np.array(a_list, dtype=float)

In [2]:
#Creating matrices
a_listoflist = [[1,2,3],[5,6,7],[8,9,10]]
a_matrix = np.matrix(a_listoflist, dtype=float)

In [3]:
# A simple function to examine given numpy object
def display_shape(a):
    print()
    print(a)
    print()
    print("Number of elements in a = %d"%(a.size))
    print("Number of dimesions in a = %d"%(a.ndim))
    print("Rows and Columns in a ", a.shape)
    print()
display_shape(a_matrix)


[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

Number of elements in a = 9
Number of dimesions in a = 2
Rows and Columns in a  (3, 3)



In [4]:
#alternate ways of creating arrays
#1.Leverage np.arange to create numpy array
created_array = np.arange(1, 10, dtype=float)
display_shape(created_array)


[1. 2. 3. 4. 5. 6. 7. 8. 9.]

Number of elements in a = 9
Number of dimesions in a = 1
Rows and Columns in a  (9,)



In [5]:
# 2. Using np.linspace to create numpy array
created_array = np.linspace(1,10)
display_shape(created_array)


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]

Number of elements in a = 50
Number of dimesions in a = 1
Rows and Columns in a  (50,)



In [6]:
# 3. Create numpy arrays in using np.logspace
created_array = np.logspace(1,10,base=10.0)
display_shape(created_array)


[1.00000000e+01 1.52641797e+01 2.32995181e+01 3.55648031e+01
 5.42867544e+01 8.28642773e+01 1.26485522e+02 1.93069773e+02
 2.94705170e+02 4.49843267e+02 6.86648845e+02 1.04811313e+03
 1.59985872e+03 2.44205309e+03 3.72759372e+03 5.68986603e+03
 8.68511374e+03 1.32571137e+04 2.02358965e+04 3.08884360e+04
 4.71486636e+04 7.19685673e+04 1.09854114e+05 1.67683294e+05
 2.55954792e+05 3.90693994e+05 5.96362332e+05 9.10298178e+05
 1.38949549e+06 2.12095089e+06 3.23745754e+06 4.94171336e+06
 7.54312006e+06 1.15139540e+07 1.75751062e+07 2.68269580e+07
 4.09491506e+07 6.25055193e+07 9.54095476e+07 1.45634848e+08
 2.22299648e+08 3.39322177e+08 5.17947468e+08 7.90604321e+08
 1.20679264e+09 1.84206997e+09 2.81176870e+09 4.29193426e+09
 6.55128557e+09 1.00000000e+10]

Number of elements in a = 50
Number of dimesions in a = 1
Rows and Columns in a  (50,)



In [7]:
# Create a matrix will all elements as 1
ones_matrix = np.ones((3,3))
display_shape(ones_matrix)
# Create a matrix with all elements as 0
zeros_matrix = np.zeros((3,3))
display_shape(zeros_matrix)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Number of elements in a = 9
Number of dimesions in a = 2
Rows and Columns in a  (3, 3)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Number of elements in a = 9
Number of dimesions in a = 2
Rows and Columns in a  (3, 3)



In [8]:
# Array shaping
a_matrix = np.arange(9).reshape(3,3)
display_shape(a_matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]

Number of elements in a = 9
Number of dimesions in a = 2
Rows and Columns in a  (3, 3)



In [9]:
uniform_rnd_numbers = np.random.normal(loc=0.2,scale=0.2,size=10)
print(uniform_rnd_numbers)

[-0.06914786  0.39187276  0.08505161  0.41197474  0.32349246  0.33867399
  0.10495481  0.31785254  0.00196702  0.39638762]
