In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.pipeline import Pipeline

In [2]:
#Data preprocessing routines
x = np.asmatrix([[1,2],[2,4]])
poly = PolynomialFeatures(degree = 2)
poly.fit(x)
x_poly = poly.transform(x)

/root/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
/root/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


In [3]:
print("Original x variable shape", x.shape)
print(x)
print()
print("Transformed x variables", x_poly.shape)
print(x_poly)

Original x variable shape (2, 2)
[[1 2]
 [2 4]]

Transformed x variables (2, 6)
[[ 1.  1.  2.  1.  2.  4.]
 [ 1.  2.  4.  4.  8. 16.]]


In [4]:
#alertnatively
x_poly = poly.fit_transform(x)

/root/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
/root/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


In [5]:
data = load_iris()
x = data['data']
y = data['target']

In [6]:
estimator = DecisionTreeClassifier()
estimator.fit(x,y)
predicted_y = estimator.predict(x)
predicted_y_prob = estimator.predict_proba(x)
predicted_y_lprob = estimator.predict_log_proba(x)

/root/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py:1014: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)


In [7]:
poly = PolynomialFeatures(n=3)
tree_estimator = DecisionTreeClassifier()
steps = [('poly', poly),('tree', tree_estimator)]
estimator = Pipeline(steps=steps)
estimator.fit(x,y)
predicted_y = estimator.predict(x)

TypeError: __init__() got an unexpected keyword argument 'n'