In [1]:
# Load libraries
from sklearn.datasets import load_iris
import numpy as np

In [2]:
data = load_iris()
x = data['data']

In [4]:
#Randomly sample 10 records from the loaded dataset
no_records = 10
x_sample_indx = np.random.choice(range(x.shape[0]), no_records)
print(x[x_sample_indx,:])


[[6.1 3.  4.9 1.8]
 [4.4 2.9 1.4 0.2]
 [6.3 2.5 4.9 1.5]
 [5.7 2.8 4.1 1.3]
 [4.6 3.6 1.  0.2]
 [5.4 3.  4.5 1.5]
 [7.1 3.  5.9 2.1]
 [6.  3.  4.8 1.8]
 [6.5 3.2 5.1 2. ]
 [6.1 2.6 5.6 1.4]]
