In [3]:
import numpy as np
from io import StringIO

in_data = StringIO("10,20,30\n56,89,90\n33,46,89")

#Read the input using numpyâ€TMs genfromtext to create a nummpy array.
data = np.genfromtxt(in_data, dtype=int, delimiter=",")
data

array([[10, 20, 30],
       [56, 89, 90],
       [33, 46, 89]])

In [4]:
# cases where we may not need to use some columns.
in_data = StringIO("10,20,30\n56,89,90\n33,46,89")
data = np.genfromtxt(in_data,dtype=int,delimiter=",",usecols=(0,1))
data

array([[10, 20],
       [56, 89],
       [33, 46]])

In [5]:
# providing column names
in_data = StringIO("10,20,30\n56,89,90\n33,46,89")
data = np.genfromtxt(in_data,dtype=int,delimiter=",",names="a,b,c")
data

array([(10, 20, 30), (56, 89, 90), (33, 46, 89)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

In [6]:
# using column names from data
in_data = StringIO("a,b,c\n10,20,30\n56,89,90\n33,46,89")
data = np.genfromtxt(in_data,dtype=int,delimiter=",",names=True)
data

array([(10, 20, 30), (56, 89, 90), (33, 46, 89)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

In [7]:
in_data = StringIO("30kg,inr2000,31.11,56.33,1\n52kg,inr8000.35,12,16.7,2")
data = np.genfromtxt(in_data,delimiter=",")
data

array([[  nan,   nan, 31.11, 56.33,  1.  ],
       [  nan,   nan, 12.  , 16.7 ,  2.  ]])